name: Daily WNBA Team Stats

on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 UTC = 7:00 AM CDT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests pandas

    - name: Run scraper
      run: |
        python WNBA/team_stats_app/wnba_team_stats_scraper.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add WNBA/team_stats_app/data/2025
        git commit -m "Add WNBA team stats for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
