name: NCAAF Team Stats app

on:
  workflow_dispatch:        # enable manual trigger
  schedule:
    - cron: "0 15 * 9-12 *" # daily 15:00 UTC, Sept–Dec
    - cron: "0 15 * 1 *"    # daily 15:00 UTC, January

permissions:
  contents: write

jobs:
  compile-team-stats:
    name: Compile weekly stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run compiler
        env:
          YEAR: 2025
        working-directory: NCAA_football/team_stats_app
        run: python compile_team_stats.py

      - name: Commit and force push changes
        working-directory: NCAA_football/team_stats_app
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/weekly_advanced_stats_2025.csv
          git commit -m "Automated update: team stats for 2025 [skip ci]" || echo "No changes to commit"
          git push origin master --force
