name: NCAA Box Scores App

on:
  workflow_dispatch:
    inputs:
      week_from:
        description: 'Start week (1–16)'
        required: false
        default: '1'
      week_to:
        description: 'End week (1–16)'
        required: false
        default: '16'
      season_type:
        description: 'regular or postseason'
        required: false
        default: 'regular'
  schedule:
    # Mondays at 12:00 UTC
    - cron: '0 12 * * 1'

permissions:
  contents: write

concurrency:
  group: ncaaf-boxscores-v2-${{ github.ref }}
  cancel-in-progress: true

env:
  YEAR: '2025'
  CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}

jobs:
  box-scores:
    name: "Box scores: scrape + compile"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verify CFBD_API_KEY is set
        run: |
          if [ -z "${CFBD_API_KEY}" ]; then
            echo "CFBD_API_KEY is not set. Add it in Settings → Secrets and variables → Actions."
            exit 1
          fi
          echo "CFBD_API_KEY present (masked)."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Scrape selected weeks (overwrite existing)
        working-directory: NCAA_football/box_scores_app
        env:
          SEASON_TYPE: ${{ github.event.inputs.season_type }}
          WFROM: ${{ github.event.inputs.week_from }}
          WTO: ${{ github.event.inputs.week_to }}
        shell: bash
        run: |
          : "${WFROM:=1}"
          : "${WTO:=16}"
          : "${SEASON_TYPE:=regular}"

          echo "YEAR=${YEAR}  weeks=${WFROM}-${WTO}  season_type=${SEASON_TYPE}"
          mkdir -p "data/weeks_${YEAR}"

          for w in $(seq "$WFROM" "$WTO"); do
            echo "Running: python box_scores_scraper.py --year \"$YEAR\" --week \"$w\" --season-type \"$SEASON_TYPE\""
            python box_scores_scraper.py --year "$YEAR" --week "$w" --season-type "$SEASON_TYPE"
            sleep 1
          done

      - name: Inspect outputs
        working-directory: NCAA_football/box_scores_app
        run: |
          ls -lah "data/weeks_${YEAR}" || true

      - name: Pull latest (avoid non-fast-forward) and commit weekly data
        working-directory: .
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git pull --rebase origin master || true
          if compgen -G "NCAA_football/box_scores_app/data/weeks_${YEAR}/*.json" > /dev/null; then
            git add "NCAA_football/box_scores_app/data/weeks_${YEAR}"/*.json
            git add "NCAA_football/box_scores_app/data/weeks_${YEAR}"/*.raw.txt 2>/dev/null || true
            git commit -m "Overwrite box score week JSON for ${YEAR}" || echo "No changes"
            git push || true
          else
            echo "No box score JSON found; skipping commit."
          fi

      - name: Run compiler (in app folder)
        working-directory: NCAA_football/box_scores_app
        run: python compile_box_scores_season.py

      - name: Pull latest (avoid non-fast-forward) and commit compiled season file
        working-directory: .
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git pull --rebase origin master || true
          if [ -f "NCAA_football/box_scores_app/data/boxscores_${YEAR}.csv" ]; then
            git add "NCAA_football/box_scores_app/data/boxscores_${YEAR}.csv"
            git commit -m "Update boxscores_${YEAR}.csv" || echo "No changes"
            git push || true
          else
            echo "No compiled season file yet; skipping commit."
          fi
