name: NCAA Box Scores (2025)

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 12:00 UTC
    - cron: '0 12 * * 1'

permissions:
  contents: write

env:
  YEAR: "2025"
  CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}

jobs:
  box-scores:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # 🔹 Run scraper (weeks 1–16)
      - name: Scrape weekly box scores
        working-directory: NCAA_football/box_scores_app
        run: |
          for w in $(seq 1 16); do
            echo "Fetching week $w..."
            python box_scores_scraper.py --year "$YEAR" --week "$w" --season-type regular
          done

      - name: Inspect weekly outputs
        working-directory: NCAA_football/box_scores_app
        run: ls -lah "data/weeks_${YEAR}" || true

      # 🔹 Compile into season CSV
      - name: Compile season file
        working-directory: NCAA_football/box_scores_app
        run: python compile_box_scores_season.py

      - name: Inspect compiled file
        working-directory: NCAA_football/box_scores_app
        run: ls -lah data/box_scores_${YEAR}.csv || true

      # 🔹 Commit JSONs and compiled CSV
      - name: Commit and push data
        working-directory: NCAA_football/box_scores_app
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage JSONs and season CSV
          if compgen -G "data/weeks_${YEAR}/*.json" > /dev/null; then
            git add data/weeks_${YEAR}/*.json
          fi

          if [ -f "data/box_scores_${YEAR}.csv" ]; then
            git add data/box_scores_${YEAR}.csv
          fi

          git commit -m "Update box scores for ${YEAR}" || echo "No changes to commit"

          # Prevent non-fast-forward errors
          git pull --rebase origin master || true
          git push
