name: NCAAF Rankings app

permissions:
  contents: write   # allow workflow to push back to repo

on:
  schedule:
    - cron: "0 12 * 9-12 1"   # every Monday at 12:00 UTC, Sep–Dec
  workflow_dispatch:

jobs:
  rankings:
    runs-on: ubuntu-latest
    concurrency:
      group: ncaa-rankings
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run weekly poll scraper
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          YEAR: 2025
        run: python NCAA_football/rankings_app/weekly_polls_scraper.py

      - name: Compile polls
        env:
          YEAR: 2025
        run: python NCAA_football/rankings_app/compile_polls.py

      - name: Commit and push if changes
        run: |
          if [ -f NCAA_football/rankings_app/polls_changed.flag ]; then
            rm NCAA_football/rankings_app/polls_changed.flag
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Update NCAA polls for ${{ env.YEAR }}"
            # ensure branch is up-to-date to avoid rejected push
            git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master || true
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          else
            echo "No changes to commit."
          fi
