name: NCAAF_apps

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why are you running this manually?'
        required: false
        default: 'manual run'
  schedule:
    # Daily at 12:00 UTC (07:00 CT) during Aug–Dec
    - cron: '0 12 * 8-12 *'
    # Daily at 12:00 UTC (06:00 CT during standard time) in January
    - cron: '0 12 * 1 *'

permissions:
  contents: write

concurrency:
  group: ncaaf-apps-${{ github.ref }}
  cancel-in-progress: false

env:
  YEAR: '2025'
  CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}

jobs:
  scrape_and_compile:
    name: Box scores: scrape + compile (daily)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run scraper
        working-directory: NCAA_football/box_scores_app
        run: python box_scores_scraper.py

      - name: Commit weekly data
        working-directory: NCAA_football/box_scores_app
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/weeks_${{ env.YEAR }}/
          git commit -m "Add week box score JSON for ${{ env.YEAR }}" || echo "No changes"
          git push

      - name: Run compiler
        working-directory: NCAA_football/box_scores_app
        run: python compile_box_scores_season.py

      - name: Commit compiled season file
        working-directory: NCAA_football/box_scores_app
        run: |
          git add data/boxscores_${{ env.YEAR }}.csv
          git commit -m "Update boxscores_${{ env.YEAR }}.csv" || echo "No changes"
          git push

  daily-elo-update:
    name: ELO update (daily)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfbd pandas

      - name: Run ELO scraper
        working-directory: NCAA_football/elo_ratings_app
        run: python weekly_elo_scraper.py

      - name: Compile ELO season data
        working-directory: NCAA_football/elo_ratings_app
        run: python compile_elo_season.py

      - name: Commit and push changes
        working-directory: NCAA_football/elo_ratings_app
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update ${{ env.YEAR }} ELO ratings" || echo "No changes to commit"
          git push

  update-rankings:
    name: Rankings (daily)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Verify CFBD_API_KEY is set
        run: |
          if [ -z "${CFBD_API_KEY}" ]; then
            echo "CFBD_API_KEY is not set. Add it in Settings → Secrets and variables → Actions."
            exit 1
          fi
          echo "CFBD_API_KEY present (masked)."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run weekly scraper
        working-directory: NCAA_football/rankings_app
        env:
          CFBD_API_KEY: ${{ env.CFBD_API_KEY }}
        run: python weekly_polls_scraper.py

      - name: Compile polls into CSV
        working-directory: NCAA_football/rankings_app
        run: python compile_polls.py

      - name: Commit & push updated data
        working-directory: NCAA_football/rankings_app
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if compgen -G "data/weeks_${{ env.YEAR }}/*.json" > /dev/null; then
            git add data/weeks_${{ env.YEAR }}/*.json
          fi
          if [ -f "data/weekly_rankings_${{ env.YEAR }}.csv" ]; then
            git add data/weekly_rankings_${{ env.YEAR }}.csv
          fi
          git diff --cached --quiet || (git commit -m "Automated update: weekly_rankings for ${{ env.YEAR }} [skip ci]" && git push)

  team-stats:
    name: Team stats (daily)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Verify CFBD_API_KEY is set
        run: |
          if [ -z "${CFBD_API_KEY}" ]; then
            echo "CFBD_API_KEY is not set. Add it in Settings → Secrets and variables → Actions."
            exit 1
          fi
          echo "CFBD_API_KEY present (masked)."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run weekly team stats scraper
        working-directory: NCAA_football/team_stats_app
        env:
          CFBD_API_KEY: ${{ env.CFBD_API_KEY }}
        run: python weekly_team_stats_scraper.py

      - name: Compile team stats into CSV
        working-directory: NCAA_football/team_stats_app
        run: python compile_team_stats.py

      - name: Commit & push updated data
        working-directory: NCAA_football/team_stats_app
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if compgen -G "data/weeks_${{ env.YEAR }}/*.csv" > /dev/null; then
            git add data/weeks_${{ env.YEAR }}/*.csv
          fi
          if [ -f "data/weekly_advanced_stats_${{ env.YEAR }}.csv" ]; then
            git add data/weekly_advanced_stats_${{ env.YEAR }}.csv
          fi
          git diff --cached --quiet || (git commit -m "Automated update: team stats for ${{ env.YEAR }} [skip ci]" && git push)
