name: Weekly Rankings Update

on:
  schedule:
    - cron: '0 12 * 8-12 MON'  # every Monday at 12:00 UTC, only from August through December
  workflow_dispatch:

permissions:
  contents: write

env:
  YEAR: '2025'

jobs:
  update-weekly-rankings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run weekly scraper
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          cd NCAA_football/rankings_app
          python weekly_polls_scraper.py

      - name: Compile polls into CSV
        run: |
          cd NCAA_football/rankings_app
          python compile_polls.py

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cd NCAA_football/rankings_app

          git pull origin main

          if compgen -G "data/weeks_${{ env.YEAR }}/*.json" > /dev/null; then
            git add data/weeks_${{ env.YEAR }}/*.json
          fi

          if [ -f "data/weekly_rankings_${{ env.YEAR }}.csv" ]; then
            git add data/weekly_rankings_${{ env.YEAR }}.csv
          fi

          git diff --cached --quiet || \
            (git commit -m "Automated update: weekly_rankings for ${{ env.YEAR }} [skip ci]" && git push origin main)
