name: WNBA apps

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Set PAT git credentials
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_SDL_PAT }}@github.com/jameskemper/sports_data_library.git

    - name: Run daily box score scraper
      run: |
        python WNBA/box_scores_app/box_scores_scraper.py

    - name: Build master season dataset
      run: |
        python WNBA/box_scores_app/compile_box_scores_season.py

    - name: Run daily player stats scraper
      run: |
        python WNBA/player_stats_app/player_stats_scraper.py

    - name: Build player master dataset
      run: |
        python WNBA/player_stats_app/compile_player_stats_season.py

    - name: Run player season stats scraper
      run: |
        python WNBA/player_stats_app/player_stats_season.py

    - name: Commit and push all data
      run: |
        git add WNBA/box_scores_app/data
        git add WNBA/player_stats_app/data
        git commit -m "Auto update: WNBA data $(date +'%Y-%m-%d')" || echo "Nothing to commit"
        git push origin HEAD:master
