name: Daily WNBA Box Scores

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC = 7AM CDT daily
  workflow_dispatch:       # Allows manual trigger too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run daily box score scraper
      run: |
        python WNBA/team_stats_app/box_scores_scraper.py

    - name: Build master dataset
      run: |
        python WNBA/team_stats_app/compile_box_scores_seasons.py

    - name: Commit and push data
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add WNBA/team_stats_app/data/2025
        git commit -m "Auto update: WNBA box scores $(date +'%Y-%m-%d')" || echo "Nothing to commit"
        git push
