name: WNBA apps

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # disables ephemeral GitHub token

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run daily box score scraper
      run: |
        python WNBA/box_scores_app/box_scores_scraper.py

    - name: Build master season dataset
      run: |
        python WNBA/box_scores_app/compile_box_scores_season.py

    - name: Commit and push data
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add WNBA/box_scores_app/data
        git commit -m "Auto update: WNBA box scores $(date +'%Y-%m-%d')" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${{ secrets.GH_SDL_PAT }}@github.com/jameskemper/sports_data_library.git
        git push origin HEAD:master
